sudo: false
dist: xenial
language: python

services:
  - docker

matrix:
    include:
        - python: 3.5
          env: TOXENV=pytest
        - python: 3.6
          env: TOXENV=pytest
        - python: 3.7
          env: TOXENV=pytest
        - python: pypy3
          env: TOXENV=pytest
        - python: 3.5
          env: TOXENV=flake8
        - python: 3.7
          env: TOXENV=flake8

cache:
  directories:
    - $HOME/.cache/pip

install:
  - pip install tox
  - if [[ $TOXENV == pytest ]]; then pip install coveralls; fi

script:
  - tox

notifications:
  email: false

after_success:
  - if [[ $TOXENV == pytest ]]; then coveralls; fi
